### ISSUE TITLE
Estado de la montura

### ISSUE THREAD

**Issue by mclopez-uma** [GLORIA-project/night-experiment-interface#1]
Es posible que un telescopio no tenga la opción de lectura ni de escritura del tracking y que el RTI devuelva "Operación no soportada". Gestionar esto adecuadamente para devolver el estado de la montura. Ahora mismo, si esto sucede (BART) se devuelve la montura a ERROR cuando realmente la montura funciona correctamente.

**Comment by fserena** [comment]
Si GLORIA no puede saber si un telescopio está TRACKING...¿que creéis que debe hacer? Teniendo en cuenta que desde el punto de vista del experimento es un estado necesario para tomar decisiones. Por ejemplo, no dejar tomar una imagen o mover con flechas hasta que la montura esté TRACKING.

**Comment by esgg** [comment]
Viendo lo que sucede tenemos dos posibilidades:
-> Añadir en el interfaz dos estados de montura.
          - Uno indicaría el estado
          - y otro si está en tracking
-> Otro sería modificar la secuencia.
         1/ Las llamadas a isSlewing y isParked no son necesarias (eliminar de la secuencia)
         2/ Llamar a getActivityState(). 
         3/ Si el resultado es STOP
                   comprobar isTracking
                            true: devolver como estado tracking
                            false: devolver como estado STOP
                            si la operación no está soportada -> devolver STOP tb
                    e.o.c
                            devolver getActivityState

Fernando, cual te parece mejor solución? En cualquiera de los dos casos, isSlewing e isParked no son necesarias.

**Comment by angelagonzalez** [comment]
Terminado de comprobar esta noche con BOOTES-2. Por mi parte se puede cerrar.

Incidencia relacionada con ésta:
https://github.com/esgg/GLORIANightExperiment/issues/31
