### ISSUE TITLE
El enlace a la webcam interior de BOOTES-1A suele aparecer roto

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/night-experiment-interface#10]
Prioridad: media

El enlace a la webcam interior de BOOTES-1A suele aparecer roto, por lo cual los usuarios no saben si el telescopio se está moviendo o no, e interpretan que la montura falla y no obedece. (Firefox, en Chrome no lo he llegado a comprobar).

Yo misma lo he experimentado hoy pero por suerte lo veía moverse en la web de BOOTES directamente, de modo que la webcam funciona.

Este problema se une al de falta de memoria en este telescopio que ocasiona mensajes de error al intentar tomar imágenes y los usuarios interpretan que todo falla cuando en realidad no es así.

![31-05-2014 22_06 ut bootes-1a error al intentar exponer 40s en m106](https://cloud.githubusercontent.com/assets/6812954/3140480/fdf5f57c-e920-11e3-922e-60f01110a1af.jpg)

**Comment by carlibiri** [comment]
Please, UPM, mirad a ver qué ocurre con esa webcam, igual la url de la webcam no está correcta...

**Comment by esgg** [comment]
Eso es debido a que B1A sólo tiene una webcam. No tiene webcam interna

**Comment by esgg** [comment]
He eliminado para B1A la segunda webcam del interfaz. Pendiente de cerrar issue.

**Comment by angelagonzalez** [comment]
Pero en la web de Bootes sí aparece y juraría que antes también se veía en Gloria.

**Comment by esgg** [comment]
Pues no la tenemos registrada. Hablaré con Mª Carmen para ver si la tienen incluida en el RTI y mañana os comento

**Comment by angelagonzalez** [comment]
Ok.

**Comment by esgg** [comment]
En el rti sólo hay registrada una webcam. Ángela puedes comprobar que hay mas de una webcam en B1A?

**Comment by angelagonzalez** [comment]
BOOTES-1A sí tiene webcam interior. Abro esta incidencia por indicación de Esteban para que se incluya en el experimento nocturno.
https://github.com/GLORIA-project/GLORIA_RTSInteractiveRTS2/issues/10

**Comment by angelagonzalez** [comment]
En pre-producción ya aparecen correctamente las imágenes de la webcam interior de BOOTES-1A.

**Comment by carlibiri** [comment]
Ángela cierra la issue cuando esté correctamente en producción, si no puedes dímelo y lo hago yo.

**Comment by angelagonzalez** [comment]
Ok. Parece  sí puedo. Lo haré.
