### ISSUE TITLE
Añadir enlaces para telescopios

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/night-experiment-interface#13]
Os paso los enlaces:

Previsión meteorológica (Da la previsión para astronomía, e incluso en XML o JSON): 
http://www.7timer.com/index.php?product=astro&lon=-6.945&lat=37.261&lang=en&ac=0&unit=metric&tzshift=0&site=

Mapa del cielo (Muestra el mapa del cielo para una localización concreta, permite configurar múltiples parámetros):
http://www.fourmilab.ch/cgi-bin/Yoursky?date=0&utc=1998%2F02%2F06+12%3A42%3A40&jd=2450851.02963&lat=37.261&ns=North&lon=6.945&ew=West&coords=on&moonp=on&deep=on&deepm=10&consto=on&constn=on&constb=on&limag=5.5&starn=on&starnm=2.0&starb=on&starbm=2.5&imgsize=640&fontscale=1.0&scheme=0&elements=

**Comment by esgg** [comment]
El mapa del cielo sale con demasiados objetos y es un poco confuso para el usuario. Para la primera versión, ¿como lo implemento?. ¿Pongo un icono que cuando se presione te redirija a la página abriéndote una nueva ventana? . 

También aparece una lista con objetos visibles (esencialmente planetas). Se podría usar para activar los objetos del catálogo pero la página es un poco dificil de parsear. Puede seguir investigando si lo consideráis interesante.

**Comment by mserraricart** [comment]
Lo primero es saber dónde y para que se quiere colocar el mapa del cielo.
Si lo que se quiere es mostrar al usuario el mapa del cielo desde la latitud/longitud del lugar pues puede ser una ventana emergente donde se muestre todo el cielo.
A mi me parece muy interesante mostrar al usuario el mismo campo del cielo que le muestra el telescopio (tanto el grande como el pequeño) para que así pueda identificar que objetos está viendo.

**Comment by angelagonzalez** [comment]
Yo resaltaría únicamente los objetos Messier y NGC. Usuarios más avanzados no necesitarán mirar ahí puesto que ya sabrán lo que van a observar de antemano y tienen programas específicos para ello.

Poner los planetas y/o la luna es un arma de doble filo ya que en varios telescopios existirán limitaciones para verlos y lo ideal es que en ellos los usuarios observen objetos de cielo profundo. Pero ya como veáis.

**Comment by angelagonzalez** [comment]
Estoy de acuerdo con Miquel y con que la ventana sea emergente. A ver si es sencillo de hacer.

**Comment by carlibiri** [comment]
Luciano is the person who can modify the main website.

**Comment by carlibiri** [comment]
Also, Esteban is going to add a link in the planets catalog, inside the night experiment, with the text "Skymap". When the users press that link, a new tab will be opened with the skymap. We think it is the best and faster option right now.

**Comment by angelagonzalez** [comment]
Checked the skymap in pre-production for TADn, OK. Tomorrow (13th Jun 2014) will be tested for the other telescopes (the latitude and longitude).

**Comment by angelagonzalez** [comment]
I've checked the coordinates for skymap in all the interactive night telescopes: BOOTES-1A, BOOTES-2, BART, D50 and TADn and are correct. I like a lot how it looks and where it is located.

If all of us agree, I propose to close this issue and continue the part related with weather on:
https://github.com/esgg/GLORIANightExperiment/issues/38
