### ISSUE TITLE
Añadir videotutoriales

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/night-experiment-interface#14]
Os paso los enlaces:

Experimento Solar:

http://youtu.be/kylY8ofpkJ0

Experimento Nocturno:

http://youtu.be/DqOHZB1hsuM

**Comment by esgg** [comment]
He añadido un botón llamado Help que despliega una ventana con el video-tutorial. Tenemos que pensar como se va a traducir, si mediante subtitulos o mediante audio

**Comment by angelagonzalez** [comment]
No se puede hacer que ponga TUTORIALS en vez de HELP? Si sólo pone help los usuarios pueden pensar que es un botón para escribir incidencias o solicitar ayuda. Creo que poniendo TUTORIALS queda más claro y además también se podrán colgar ahí los manuales escritos que estoy preparando.

Respecto al idioma como mínimo habrá que incluir el doblaje al Inglés con audio. Yo di los guiones en Inglés sólo falta que alguien los doble. Voy a informarme de cómo está el tema y os digo. 

Eso sí, es necesario hacer un video nuevo o sólo daros la grabación de voz ya ajustada en tiempo y vosotros le ponéis un botón de cambio de idioma o algo así? Ser puede hacer? Creo que alguien comentó que sí pero no recuerdo quién fue.

**Comment by angelagonzalez** [comment]
No veo el botón de los videotutoriales.

En Bologna se dijo de ponerlos junto a los experimentos, es decir aquí:

http://users.gloria-project.eu/reservations/#/new

O junto a la lista de reservas, ya que cada usuario como mucho tendrá 2 reservas simultáneas y había bastante espacio para añadir botones. Es decir, aquí:

http://users.gloria-project.eu/reservations/#/pending

Por favor, que el botón ponga 'TUTORIALS'.

Gracias.

**Comment by esgg** [comment]
Ya lo he cambiado. Os aviso cuando lo suba a producción

**Comment by angelagonzalez** [comment]
Para el experimento Solar no se ha incluido botón de enlace a tutorial.

**Comment by angelagonzalez** [comment]
DEFINITIVO:
Esto está consensuado con Carlos y con Alberto:
- Quitar el botón 'HELP' de dentro de los experimentos. En los experimentos sólo puede haber botones del experimento en sí.
- Añadir el botón 'TUTORIALS' dentro del cual se colgarán todos los videotutoriales (solar y nocturno) y todos los futuros manuales (que estoy preparando).
- El botón 'TUTORIALS' se colocará en los siguientes AMBOS dos sitios:

*Junto a los Experimentos:
http://users.gloria-project.eu/reservations/#/new
![junto a los experimentos](https://cloud.githubusercontent.com/assets/6812954/3187964/6b5c93c6-ecb6-11e3-985b-c7a4a9a6d13a.jpg)

*Y junto a las Reservas:
http://users.gloria-project.eu/reservations/#/pending
![botn junto a las reservas](https://cloud.githubusercontent.com/assets/6812954/3187976/84df299e-ecb6-11e3-9785-2692d3c7e602.jpg)

Saludos.

**Comment by angelagonzalez** [comment]
(Esta incidencia viene de aquí:
https://github.com/GLORIA-project/reservations-interface/issues/17)

**Comment by carlibiri** [comment]
Veo bien donde comenta Ángela, qué te parece Fernando?

**Comment by fserena** [comment]
Perfecto, en cuanto lo tengamos listo lo subimos a producción.

**Comment by angelagonzalez** [comment]
To summarize up, here is the list of links to Tutorials in English and in Spanish (4 in total for the moment):
- Night Experiment (English): http://youtu.be/rFvY3ZBWnJ8
- Solar Experiment (English): http://youtu.be/Q7ttk_bGPkQ
- Experimento Nocturno(Español): http://youtu.be/DqOHZB1hsuM
- Experimento Solar (Español): http://youtu.be/kylY8ofpkJ0

It would be great that clicking on the button 'TUTORIALS' a new sub-page containing the Youtube snapshots of all of them appears, so that the user can easily click on each one separately.

NOTE: Once the new changes on GLORIA website are uploaded, it will be necessary to re-record the Night Experiment Tutorial, as many things have changed. At the moment, version 1.0 it's good until there is available another one.

**Comment by fserena** [comment]
The links to the experiment tutorials are now available at the "New reservation" view.

**Comment by angelagonzalez** [comment]
1) Hola, mirando en producción, al pinchar en el botón 'Tutorials' sólo hay uno (el del experimento nocturno en Español). Deberían salir los 4: el solar y el nocturno tanto en Inglés como en Español.

2) Aparte, parece que hay algún problema al crear reservas en el TADs, pues a veces abre los tutoriales en vez de llevarte al calendario.

**Comment by fserena** [comment]
1) Cuando haces click en el botón Tutoriales deben salir los dos del idioma que tengas seleccionado. Si estás en español salen los dos en español (scroll) y en el resto de idiomas salen en inglés. Es posible que tengas que borrar la caché de tu navegador.

2) No soy capaz de reproducir este error en ningún navegador. Me puedes decir qué navegador y qué versión estás usando?

**Comment by angelagonzalez** [comment]
1) Cierto al hacer scroll salen los dos, pero se aprecia muy poco el de abajo, ¿no se puede poner la ventana más alta para que se vea mejor el de abajo?

2) Lo estamos probando con dos ordenadores diferentes: 
A) Firefox 30 -> Al intentar hacer reservas en Español en el solar (al pinchar en el rectángulo grande de TADs) se abre una nueva pestaña que te lleva a Youtube y al tutorial del solar en Español. Al intentar reservar en el solar en Inglés, hace igual pero llevándote al tutorial solar en Inglés.

En los nocturnos no pasa.

B) Firefox 29.0.1 -> No ocurre este problema pero al pinchar al botón SALIR no hace nada (no sale de GLORIA). El botón está como congelado.

Con Chrome Versión 35.0.1916.153 m ocurren los fallos A y B, y además hay que pinchar unas 10 o 15 veces en los rectángulos grandes de "Experimento Solar" y "TADs" para que haga algo.

**Comment by fserena** [comment]
1) Si, lo cambiamos.

2) A) No consigo reproducirlo, pero miro a ver qué puede pasar. Aunque esta tan extraño que no sé si voy a poder detectarlo.

2) B) Es cierto, en ocasiones el botón de salir no responde. Ni siquiera sale la manita, es como si hubiese algo por delante.

Lo de que tengas que pinchar 10 o 15 veces...¿tienes pila en el ratón? :D
Ahora en serio: antes no te pasaba?

**Comment by angelagonzalez** [comment]
Antes no pasaba, no. Lo de las 10-15 veces, después de tanto darle, al final te lleva a youtube y al tutorial. Durante las 10-15 veces no sale la manita tampoco. Para reproducirlo quizás podríais probar entrando con otro ordenador y con otro usuario e intentando hacer una reserva en el tad solar con Chrome y con Firefox.

**Comment by angelagonzalez** [comment]
1º) En http://users.gloria-project.eu/reservations/#/new en "Elige un telescopio", tanto en Firefox 30 como en Chrome Versión 35.0.1916.153 m, tanto versión Inglesa como Española, no aparece la manita al pasar por encima de TADs (del título en mayúsculas).

2º) Ahora, al pincharle varias veces en la versión española, de repente empieza a sonar el audio del tutorial del TADsolar (pero sin llevarte a la web de youtube).

**Comment by fserena** [comment]
Actualizado con los cambios sugeridos. 
La ventana de los tutoriales ahora es más alta y no debería haber problemas de bloqueo de ratón en ningún navegador (espero).

**Comment by angelagonzalez** [comment]
Estaría todo OK salvo una cosa:

en los navegadores en los que no he borrado las caché (Chrome e IExplorer), dado que ahora los tutoriales se visualizan dentro de la propia web de GLORIA, si le damos a "Cerrar" (o a 'Close'), o pinchamos en los laterales, sin haber pausado previamente el vídeo, sigue sonando el audio aunque ya nos hayamos salido totalmente de "Tutoriales".

Con Firefox con la caché borrada no ocurre esto.

Al igual que en la incidencia de Aladin, si no es algo sencillo de resolver creo que corresponde a Carlos decidir si cerramos la incidencia.

Saludos.

**Comment by angelagonzalez** [comment]
Acabo de descubrir que en el móvil también ocurre esto (Android, teléfono nuevo).

**Comment by angelagonzalez** [comment]
El tema de caché continúa en: https://github.com/GLORIA-project/night-experiment-interface/issues/22
