### ISSUE TITLE
Pre-producción experimento nocturno CAMBIOS

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/night-experiment-interface#16]
1) Cambiar el texto del botón 'TUTORIAL' por 'INFO'.

2) En el TIP nº 1 cambiar el texto: "Enlarge the webcam images by moving the pointer over them, to get to see the telescope movement."
por:
"Enlarge the webcam images by moving the pointer over them, to see the telescope movement."

3) En los TIPs nº 3, 4 y 5, cambiar la palabra 'Search' por 'Find'.

4) Eliminar las 'i' azules que hay junto a montura y a la CCD porque no tienen ninguna función.

5) Bajar el botón 'INFO' hasta la altura de la parte de arriba del círculo central para que sea visible durante todo el experimento y no desaparezca por arriba al hacer scroll de pantalla (ver captura de pantalla).

6) Que la banda de color horizontal de los tips sea naranja, no roja, para que no parezcan mensajes de error.

7) Que al pulsar 'INFO' dos veces (desactivar y activar tips) vuelva al tip número 1 (consume mucho tiempo volver por ejemplo desde el 8 al 1 buscando el rectangulito por toda la pantalla).

![09-06-2014 botn de tips](https://cloud.githubusercontent.com/assets/6812954/3215216/fb61224e-efbc-11e3-991e-547657b5d974.jpg)

**Comment by esgg** [comment]
Cambios completados: pendiente de revisión.

**Comment by angelagonzalez** [comment]
1) No sale bien el botón. Casi no se ve. Probado en Firefox y Chrome (ver captura de pantalla).
2) Ok
3) Ok
4) Ok
5) Hace falta bajarlomás, el botón se sigue yendo por arriba al hacer scroll hacia abajo (ver captura).
6) Ok
7) Ok
8 nueva) El TIP nº 1 se sale de la pantalla por la izquierda (ver captura).
9 nueva) Sólo llega al TIP nº 10: 'Exposure Time Selector'. Faltarían del 11 al 13, o hasta el 16 conforme al minitutorial original.

Gracias.

![10-06-2014 modificaciones tips](https://cloud.githubusercontent.com/assets/6812954/3232432/23d93f98-f0b4-11e3-8ce5-11bf76c818eb.jpg)

**Comment by esgg** [comment]
1) Es debido a que el texto solo existe para la versión inglesa y debes tener por defecto la española (los textos no están traducidos todavia)
9) Creo q es debido a que este telescopio sólo tiene una ccd, por lo que el control del ojo aparece desactivado. Lo compruebo mañana. Solo he podido probarlo con el tad

**Comment by esgg** [comment]
1) Cambiado para versión en inglés y español
5) Bajado
8) Cambiado de lugar. Sale en la parte superior
9) Arreglado pero no probado en todos los telescopios

**Comment by angelagonzalez** [comment]
Todo conforme y probado en TADn. Falta comprobar el resto de telescopios.

**Comment by angelagonzalez** [comment]
- Los TIPs son correctos en todos los telescopios salvo en lo referente a filtros, porque:
- En pre-producción no aparece desplegable de filtros para ningún telescopio: BOOTES-2. BART ni D50. En teoría debería aparecer al menos para estos tres.

**Comment by carlibiri** [comment]
Esteban confirmanos si es porque está en pre-producción o es un fallo del interfaz del experimento al realizar las modificaciones.

**Comment by angelagonzalez** [comment]
Es porque estaba en la  de otro usuario. Si os parece la cierro cuando esté en producción.

**Comment by esgg** [comment]
Todavía no está en producción, se subirá hoy.

**Comment by angelagonzalez** [comment]
Todo ok, los filtros de cada telescopio también.
