### ISSUE TITLE
En BOOTES-1A no se transfieren las imágenes en el experimento

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/night-experiment-interface#17]
Prioridad Alta.

En la reserva de las 21UT del 19-06-2014 el usuario tomó varias imágenes del mismo objeto (Saturno) y no se transferían al experimento.

Hemos comprobado que dichas imágenes sí están en el RTI.

**Comment by carlibiri** [comment]
Acabo de hablar por teléfono con Esteban. Cuando aparece trasferring en el experimento significa que se está descargando la imagen en el interfaz del experimento. Resulta que en B1A, las imágenes tienen un tamaño muuy grande, si se pierde la conexión, se quedaría bloqueado... Quizás, sería interesante añadir ahí un timeout para que notifique al usuario de que no ha podido descargar la imagen y ponerle un botón de reintentar...

Qué os parece?

**Comment by angelagonzalez** [comment]
Anoche (20-06-2014) a las 21 UT se produjo el mismo problema. Un usuario dice: "BLOQUEADO 15 min en transfering".

**Comment by esgg** [comment]
He comprobado que la imagen se registró correctamente en el sistema. Fue una imagen de saturno.

Tengo que comprobarlo, pero si el usuario vuelve a dar a exponer, se reinicia la exposición. Creo que añadir otro botón para reintentarlo puede ser confuso para el usuario.

Voy a estudiar lo del timeout. Creo que no será fácil debido a los comandos que utilizamos. Mañana os lo confirmo.

**Comment by angelagonzalez** [comment]
- No he tenido el problemas con esta incidencia ayer sábado 21/06/2014 21:45 UT con imágenes de 30 segundos (el usuario dice que sí, pero entré en su reserva y yo podía ver y descargar sus imágenes).
- Hoy domingo 22/06/2014 21 UT he probado yo misma BOOTES-1A con M92 y M13 y exposiciones de 30 segundos y todo ha ido bien. De hecho, lo puntúo con un 10 porque he abierto las imágenes con Aladin y me parecen muy buenas.

Por favor, indicadme sugerencias para el usuario (me voy a poner en contacto con él): ¿que vacíe la caché? ¿Que use Firefox 30 o Android (es lo que usé yo hoy y ayer respectivamente)? ¿Que use Chrome? ¿Que actualice los navegadores sean cualesquiera los que tenga?

Si os parece cerramos esta issue hasta que otro usuario vuelva a reportar el mismo error.

**Comment by esgg** [comment]
Creo que no tiene nada que ver con la versión de navegador que usa.
Se pueden decir varias cosas:
1º/ Que observe si la imagen sale en el álbum, allí podrá descargársela o visualizarla.
2º/ Si ve que tarda mucho puede hacer un F5 o reload de la página. Eso reseteará el experimento y podrá volver a tomar imágenes. Además le saldrá la imagen tomada en el álbum.

¿Qué velocidad de conexión a Internet usas?

**Comment by angelagonzalez** [comment]
Yo o el usuario? Yo 5 megas creo. El usuario no sé.

**Comment by carlibiri** [comment]
Sería interesante preguntarle al usuario. Esto sólo le ocurre a un usuario o hay más?

**Comment by angelagonzalez** [comment]
De momento sólo a uno, pero lo reporta constantemente cada día desde el jueves.

**Comment by carlibiri** [comment]
Si es sólo a ese usuario, pregúntale qué tipo de conexión utiliza, si es ADSL, fibra o utiliza una conexión a través de móvil 3G o algo así... Yo cuando me conecto con un modem 3G tengo problemas también para descargar las imágenes, pero es porque la conexión es más lenta. Otra cuestión, si el usuario se conecta desde sudamérica (no lo sé) en esos paises la conexión suele ser también peor...

**Comment by angelagonzalez** [comment]
Gracias Carlos y Esteban. Os contaré lo que me dice.

**Comment by angelagonzalez** [comment]
¿Esteban cómo te ha ido? Vi que habías tomado al menos 3 imágenes.

**Comment by esgg** [comment]
Si, tome tres imágenes (de saturno y m15) aunque me salieron muy saturadas
:). Tanto el movimiento de montura como la exposición funcionaron sin
problema.

Mi conexión es de 10 megas así que no parece un problema de velocidad.
Cuando sale el mensaje de TRANSFERING se puede volver a exponer, puede ser
una forma de evitar ese "bloqueo".

2014-06-24 0:40 GMT+02:00 angelagonzalez notifications@github.com:

> ¿Esteban cómo te ha ido? Vi que habías tomado al menos 3 imágenes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GLORIA-project/night-experiment-interface/issues/17#issuecomment-46911578
> .

## 

---

Esteban GONZÁLEZ GUARDIA<e <eg.guardia@gmail.com>gonzalez@ciclope.info>
Dep. de Arquitectura y Tecnología de Sistemas Informáticos
Facultad de Informática
Universidad Politécnica de Madrid               Tel. : (+34) 91 336 5016
C/ Campus de Montegancedo, s/n
28660 Boadilla del Monte - Madrid (Spain)   FAX  : (+34) 91 336 7373

---

**Comment by carlibiri** [comment]
A ver si pudieras meter un timeout o algo así...

**Comment by esgg** [comment]
Hay una solución un poco "chapuza" de meter un timer que cambie el mensaje pero no puede abortar el proceso de descarga de la imagen, pues este lo controla el navegador. Si te parece bien esta solución la implemento lo antes posible.

**Comment by carlibiri** [comment]
No lo veo mala opción, qué opina Ángela?

**Comment by angelagonzalez** [comment]
El usuario no contestó al correo que le envié, y estuvo conectado anoche. No se ha observado este problema en más usuarios, y además ha sido comprobado por Esteban y por mí con diferentes ordenadores y anchos de banda.

Si es realmente necesario lo del timer adelante. Si no, yo cerraría esta issue ya que hay cosas más urgentes.  Si os parece bien, claro. 

Si más adelante se volviera a producir el problema la reabrimos.

**Comment by carlibiri** [comment]
Totalmente de acuerdo con Ángela. la cierro...
