### ISSUE TITLE
Problema cambio de filtros

### ISSUE THREAD

**Issue by esgg** [GLORIA-project/night-experiment-interface#2]
Prioridad: Media

Se debería comprobar porque los filtros en algunas ocasiones no se cambian. Parece que es un fallo de comunicaciones, pero habría que comprobarlo bien.

no cambio de filtros: reservas 2293, 2291, 2294 y 2292, 5 de Abril, BOOTES-2.

**Comment by esgg** [comment]
No se estaba llamando a la función de cambio de filtros.

**Comment by esgg** [comment]
Ya he corregido el problema. 

Quedo a la espera para su cierre

**Comment by carlibiri** [comment]
Hola Ángela, podrías probar esto? Cuando lo pruebes, si va todo bien cierra la issue.

**Comment by angelagonzalez** [comment]
Creo que esta issue está repetida. Estuve escribiendo en ésta, pongo enlace para que se relacionen las dos:
https://github.com/esgg/GLORIANightExperiment/issues/26

**Comment by angelagonzalez** [comment]
Ok comprobado. Por mi parte se puede cerrar.
