### ISSUE TITLE
Que no se cachee la página en los experimentos nocturnos

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/night-experiment-interface#22]
Cambiar los meta del header del HTML para que no se cachee la página en los Experimentos Nocturnos (deshabilitar el cacheo del navegador).

**Comment by angelagonzalez** [comment]
(Los problemas de caché provienen de:
https://github.com/GLORIA-project/night-experiment-interface/issues/14 y en:
https://github.com/GLORIA-project/reservations-interface/issues/26).

**Comment by esgg** [comment]
Cambiado para que no cachee tal como se realiza en el solar. Pendiente de cierre

**Comment by angelagonzalez** [comment]
El enlace a Aladin sí se muestra. Pero el audio de los tutoriales sigue sonando al cerrrar la ventana si no se le da antes a STOP dentro de la pantalla de Youtube.

**Comment by angelagonzalez** [comment]
Resuelto y comprobado.
