### ISSUE TITLE
No se generan bien los JPEG a partir de los FITS

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/night-experiment-interface#23]
Se ha desvelado por fin el misterio de Saturno: no es que salga saturado con todos los filtros y todos los tiempos de exposición por pequeños que se establezcan, sino que el convertidor de FITS a JPEG no lo convierte bien.

Ejemplo:
- JPEG de Saturno generado por GLORIA con filtro UKIRT_Y y 4s de exposición :
  ![saturn](https://cloud.githubusercontent.com/assets/6812954/3418849/ed50f9e4-fe4f-11e3-9f23-2069d49bcd1d.jpg)
- JPEG de la misma imagen de Saturno, generada con Aladin a partir del mismo FITS:
  ![saturn bis](https://cloud.githubusercontent.com/assets/6812954/3418859/3f237670-fe50-11e3-9010-75515a76a260.jpg)

REVISAR EL CONVERTIDOR DE FITS a JPG, sobre todo es importante para planetas.
Para objetos de cielo profundo sí interesa usar ZSCALE pero para planetas, es mejor usar MINMAX.

**Comment by mclopez-uma** [comment]
Para el caso de RTS2, que entiendo que es el ejemplo que indicas del filtro UKIRT_Y, la conversión a JPG la hace RTS2, el RTI no entra en ese procesado, sólo le pide la imagen en ese formato.

**Comment by angelagonzalez** [comment]
Ok, gracias.  Investigaré al respecto y vuelvo a escribir.

**Comment by mclopez-uma** [comment]
Me dice Mates que el método para la generación de JPEG que él tiene no está enlazado con el XMLRCP, así que el RTI no lo puede utilizar. Dice que hablará con Standa, que lo tiene que ver en los viajes que tiene que hacer ahora.

**Comment by angelagonzalez** [comment]
Hablado con P.K. Se soluciona haciendo q=0 en el caso de planetas.

**Comment by mclopez-uma** [comment]
Hecho

**Comment by carlibiri** [comment]
Por favor, que alguien lo pruebe y confirme si se puede cerrar esta tarea. Un saludo.

**Comment by carlibiri** [comment]
Juan envía una imagen tomada con Bootes2 de Saturno en el que se ve correctamente en jpg. Entiendo que el cambio se ha realizado correctamente. Si no fuera así se podría reabrir la incidencia.
