### ISSUE TITLE
PRIORIDAD MÁXIMA - La interfaz de GLORIA vuelve a ser la antigua

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/night-experiment-interface#27]
03 Julio 2014 21-21:30 UT

Acabo de entrar a supervisar las reservas de los usuarios y me he encontrado que la interfaz de usuario vuelve a ser la antigua.

Se han perdido todos los cambios. Vuelve a salir el ojo para tomar imágenes, la cámara en pequeño, ojos en telescopios que no deben tenerlo, se ha perdido el botón INFO del mini tutorial, los sensores atmosféricos de los telescopios salen vacíos.

¿Qué ha ocurrido? Es urgente, por favor miradlo. Adjunto capturas de pantalla de la situación:

BOOTES-1A:
![bootes-1a](https://cloud.githubusercontent.com/assets/6812954/3476064/72b35b60-02f9-11e4-9a59-bd0ed9bdd7ba.jpg)

BART:
![bart](https://cloud.githubusercontent.com/assets/6812954/3476068/7a89a3da-02f9-11e4-9706-a33bbee9b6be.jpg)

D50:
![d50](https://cloud.githubusercontent.com/assets/6812954/3476080/8d621f96-02f9-11e4-8e69-9ee38595a933.jpg)

TADn:
![tadn](https://cloud.githubusercontent.com/assets/6812954/3476083/929c4dec-02f9-11e4-96b5-8dd57a786388.jpg)

BOOTES-2 estaba cerrado por mal tiempo (e indica CLEAR).

**Comment by esgg** [comment]
Pues no sé que ha pasado, ayer no subí ningún cambio. He vuelto a subir la nueva, por favor, podéis probar alguno?

**Comment by carlibiri** [comment]
Esteban, pregunta a Canalcloud a ver si es que han restaurado una copia de
Seguridad antigua...

Si no habéis tocado nada vosotros tienen que haber sido ellos...

Un saludo

El viernes, 4 de julio de 2014, esgg notifications@github.com escribió:

> Pues no sé que ha pasado, ayer no subí ningún cambio. He vuelto a subir la
> nueva, por favor, podéis probar alguno?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GLORIA-project/night-experiment-interface/issues/27#issuecomment-48011921
> .

## 

---

Carlos J. Pérez del Pulgar Mancebo
Departamento de Ingeniería de Sistemas y Automática
UNIVERSIDAD DE MALAGA
www.isa.uma.es/cperez

---

**Comment by esgg** [comment]
Es posible pero raro porque esta copia es muy antigua. Y una restauración debería haber afectado al resto de la web y de los servicios.

**Comment by angelagonzalez** [comment]
Anoche entré en TADn en la reserva de otro usuario y parece que sí estaba cargada la versión nueva.
