### ISSUE TITLE
Update the link to the Spanish Night Experiment Tutorial

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/night-experiment-interface#32]
It is necessary to update the link to the Spanish Night Experiment Tutorial on:

http://users.gloria-project.eu/reservations/#/new -> "TUTORIALES"

as it is already available the version 2.

The NEW LINK is:    http://youtu.be/l8IcB7AD9ws

Regards.

**Comment by angelagonzalez** [comment]
The link has been substituted but the new night tutorial is only shown if the user erases the cache. Please, try not to cache the page. Thanks.

**Comment by angelagonzalez** [comment]
Please look into de cache issue. A user reported just today the following:

'Usando el TADn hay diferencias de interfaz entre el tutorial y la realidad'.

Users don't know they must erase their cache browsers.

Thanks.

**Comment by lnicastro** [comment]
Should we have on the website an automatic announcement window/section/div/else that we can switch on and off for informational messages? Of course this would easily overcome any cache issue.

p.s. I know programmers are evaporating and I haven't seen anything implemented of my suggestions, but you never know.

**Comment by angelagonzalez** [comment]
The link to the tutorial in Spanish is the old one again!! Why?

**Comment by esgg** [comment]
done
