### ISSUE TITLE
No se pueden descargar las imágenes obtenidas

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/night-experiment-interface#4]
No puedo descargar las imágenes, los botones para descargar JPG y FITS no aparecen.

**Comment by esgg** [comment]
Normalmente sucede porque el usuario tiene un zoom en el navegador y no pinta correctamente los botones. ¿puedes confirmarme esto? ¿Qué navegador usas?

**Comment by carlibiri** [comment]
Lo acabo de mirar con Esteban, la idea sería colocar los botones para descargar arriba, con esto se podría quedar resuelto de forma provisional.

**Comment by carlibiri** [comment]
Esteban coloca los enlaces arriba y se resuelve el problema.
