### ISSUE TITLE
No puedo realizar observaciones a objetos que supuestamente están por encima del horizonte

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/night-experiment-interface#5]
Os paso un listado de objetos, al intentar observarlos con Bootes 1 y 2, me dice que el objeto no se puede alcanzar:

M3
M5
M92
M44
M13
M92
M5

Igual me he equivocado en algo, please comentadme...

**Comment by angelagonzalez** [comment]
Yo he obtenido el mismo error en BOOTES-2 el 26-05-2014 a las 22:00, 22:15 y 22:30 UT (reservas 4079, 4084 y 4085), cuando apuntaba POR NOMBRE a varios objetos que estaban bastante altos como: M106, M51, Arcturus, Vega, NGC 4217. Introduciendo la búsqueda POR COORDENADAS sucede lo mismo. En cambio, buscando POR ICONOS DE PLANETAS funciona bien y no da error.

Me ocurrió lo mismo con D50 el 25-05-2014 a las 21:30 UT (Reserva 4023), cuando apunté a M106 que estaba por encima del horizonte también.

En BOOTES-1A no he observado este problema.

Quizá cuando se implementó este nuevo mensaje de error en la interfaz (el de ALERT: Impossible to reach the target", adjunto captura de pantalla de lo que reporto sobre BOOTES-2 de la noche del 26 de Mayo), por alguna razón se ha inhabilitado la búsqueda por nombre de objetos y por coordenadas, y sólo funciona con búsqueda de planetas.
![26-05-2014 22_09ut fallo de montura en bootes-2](https://cloud.githubusercontent.com/assets/6812954/3103710/3a74589a-e65b-11e3-9a9d-9c9c32fb8405.jpg)

**Comment by carlibiri** [comment]
El error estaba en que el RTI no estaba correctamente desplegado. Anoche lo probé y funcionó correctamente. Cierro el issue.
