### ISSUE TITLE
No aparece el cuestionario después de la reserva

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/night-experiment-interface#6]
No aparece el cuestionario cuando se me acaba la reserva, me aparece el texto, pero no el cuestionario...
![image](https://cloud.githubusercontent.com/assets/7371595/3085727/36f1396a-e519-11e3-9209-3653d1712184.png)

**Comment by fserena** [comment]
Creo que Esteban lo ha cambiado y ahora lo que proporciona es un link. El problema es que a simple vista no se ve. Si pasas el ratón por las palabras "questionnaire" o "cuestionario" se marca y puedes hacer click.

**Comment by esgg** [comment]
Me pidió Ángela que cambiara el cuestionario. Como tenemos problemas para detectar el idioma y mostrar el cuestionario completo, se añadieron los links. A simple vista, los enlaces no aparecen con el subrayado y de distinto color.

**Comment by carlibiri** [comment]
OK, añadid el texto "pulse aquí" con el hipervínculo. Lo acabo de comentar con Estaban.

**Comment by carlibiri** [comment]
Hecho y comprobado!!
