### ISSUE TITLE
Cambiar la forma en la que se cambian los filtros

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/night-experiment-interface#7]
Comenta Esteban que lo ha resuelto, pendiente probar por parte de Ángela...

**Comment by angelagonzalez** [comment]
OK. He intentado varias veces pero últimamente aparece mucho el error de que no se puede alcanzar el objeto en BOOTES-2 y en D50, y en BART no he conseguido mover el telescopio todavía, así que no he llegado a tomar imágenes. Sigo intentando.

**Comment by carlibiri** [comment]
En D50 y BART parece que hay mal tiempo. en BOOTES-2 yo he probado a moverlo a M80 y M81 y ha funcionado perfectamente...

**Comment by angelagonzalez** [comment]
¿Te refieres a que funciona bien el cambio de filtros?

**Comment by carlibiri** [comment]
Nop, me refería a que ahora sí que funciona el apuntado al objeto, era un fallo en el despliegue del RTI, lo ví ayer con Mª Carmen. Please, prueba cuando puedas el cambio de filtros y si funciona cierra el issue o dimelo y lo cierro yo.

Muchas gracias Ángela!!

**Comment by angelagonzalez** [comment]
Ok Carlos, probaré esta noche en BOOTES-2.

**Comment by angelagonzalez** [comment]
Aún sin poder probarlo en BOOTES-2.

**Comment by angelagonzalez** [comment]
Veo que esta incidencia había quedado olvidada y está relacionada con ésta:
https://github.com/esgg/GLORIANightExperiment/issues/26
y con ésta:
https://github.com/GLORIA-project/night-experiment-interface/issues/2
que están ambas cerradas.

De modo que cierro ésta también.
