### ISSUE TITLE
Problemas al introducir las coordenadas a mano

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/night-experiment-interface#8]
Al seleccionar un target por coordenadas no se ven bien las cifras que se escogen. Además, no permite introducir decimales en los segundos de ascensión recta.

**Comment by angelagonzalez** [comment]
Ejemplo de cómo debería ser:

RA         Dec

15 34 23.27 +55 23 34.7

**Comment by esgg** [comment]
Es posible que sea por el zoom. ¿Qué zoom tiene en el navegador?

No hemos tenido en cuenta los decimales en los segundos. ¿Cuantos decimales añadimos?

**Comment by carlibiri** [comment]
Dos decimales, no creo que sea por el zoom, pero lo pruebo yo y te pongo captura de pantalla para que lo veas...

**Comment by angelagonzalez** [comment]
- O 2 decimales para RA y 1 para DE.
- O 1 decimal para RA y ninguno para DE.

Los BOOTES admiten la primera opción.

El navegador no tenía ningún zoom.

**Comment by angelagonzalez** [comment]
En Firefox no se ven bien las coordenadas pero en Chrome sí. Adjunto captura de pantalla.
![31-05-2014 coordenadas no se ven en firefox s en chrome](https://cloud.githubusercontent.com/assets/6812954/3140173/ba7de2b0-e90b-11e3-92ca-af4e2de35aa1.jpg)

**Comment by esgg** [comment]
Las listas son malos elementos para poner decimales. Quizás habría que sustituirlos por cuadros de texto para introducir los valores. ¿Qué puede resultar más útil para un usuario?

**Comment by carlibiri** [comment]
Hola Esteban, mete cuadros de texto mejor, mucho más fácil. Lo que sí habría que indicar es si los decimales se ponen con "." o con ",". Pon al lado de los cuadros de texto algo que lo indique...

**Comment by angelagonzalez** [comment]
Totalmente de acuerdo.

**Comment by esgg** [comment]
Se ha cambiado en el sistema de coordenadas. Ahora se introducen mediante campo de texto. Faltaría un mensaje explicativo asociado.

**Comment by carlibiri** [comment]
Hola Esteban, en cuanto pongas el mensaje explicativo puedes cerrar la issue. Muchas gracias.

**Comment by esgg** [comment]
He añadido un mensaje explicativo sobre las coordenadas a introducir. Quedo a la espera del cierre de esta issue.

**Comment by angelagonzalez** [comment]
Comprobado con BOOTES-2 en Firefox. No he visto el modo de introducir decimales pero considero que por ahora es suficiente así. Por mi parte se puede cerrar.
